[package]
name = "retro-wicket-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
itertools = "0.13.0"
nom = "7.1.3"
proc-macro2 = "1.0.88"
quote = "1.0.37"
syn = { version = "2.0.79", features = ["full"] }
urlencoding = "2.1.3"
